http:
  routers:
    todo:
      rule: "PathPrefix(`/todo`)"
      service: todo
      middlewares:
        - "todo-auth"
        - "todo-rate-limiter"
        - "todo-stripprefix"

  middlewares:
    todo-stripprefix:
      stripPrefix:
        prefixes:
        - "/todo"
    todo-auth:
      forwardAuth:
        address: "http://auth:3000/parse"
        trustForwardHeader: true
        authResponseHeadersRegex: "^X-"
    todo-rate-limiter:
      forwardAuth:
        address: "http://rpm-limiter:3000"
        trustForwardHeader: true

  services:
    todo:
      loadBalancer:
        servers:
        - url: http://todo:3000/